version: '3.9'

services:
  # WordPress Dev installation
  wp:
    container_name: wp
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    volumes:
      - ../php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ../../public:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    links:
      - db
    extra_hosts:
      - "${LOCAL_DOMAIN}:${IP}"

  # WP CLI for import export etc.
  wpcli:
    container_name: wpcli
    image: wordpress:cli
    volumes:
      - ../php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ../../public:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
      - wp
  
  # phpMyAdmin
  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:8080:80
    links:
      - db:db

  # MySQL Database
  db:
    container_name: mysql
    image: mariadb:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ../../_db:/docker-entrypoint-initdb.d
      - ${LOCAL_MYSQL_PATH}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  # Build certificates for nginx.
  mkcert:
    container_name: mkcert
    build: ./mkcert-dev
    image: mkcert-dev
    depends_on:
      - wp
    environment: 
      domain: ${LOCAL_DOMAIN}
    volumes:
      - ../nginx/certs/:/root/.local/share/mkcert

  # Nginx for ssl certificate
  nginx:
    container_name: nginx
    image: nginx:1.19.10-alpine
    restart: unless-stopped
    depends_on:
      - db
      - wp
    environment:
     - NGINX_HOST=${LOCAL_DOMAIN}
    volumes:
      - ../nginx/certs/:/etc/nginx/certs
      - ../nginx/logs:/var/log/nginx
      - ../nginx/conf.d:/etc/nginx/conf.d
    command: nginx -g "daemon off;"
    ports:
      - ${IP}:80:80
      - ${IP}:443:443